name: Test Build
on:
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Test Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
            submodules: 'true'
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Prepare dependencies
        run: npm install
      - name: Build site
        run: npm run build
